spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptoApp
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: "/api/v1"

